use std::net::SocketAddr;

use anyhow::{Result, anyhow};
use futures::never::Never;
use kameo::actor::{ActorRef, Spawn as _};
use kameo_actors::scheduler::{Scheduler, SetInterval};
use log::{error, info};
pub use sequencer_core::config::*;
use sequencer_executor_actor::ExecutorActor;
use sequencer_rpc_server_actor::RpcServerActor;
use tokio::select;

/// Handle to manage the sequencer and its tasks.
///
/// Implements `Drop` to ensure all tasks are aborted and the RPC server is stopped when dropped.
pub struct SequencerHandle {
    executor_ref: ActorRef<ExecutorActor>,
    rpc_server_ref: ActorRef<RpcServerActor>,
    scheduler_ref: ActorRef<Scheduler>,
    addr: SocketAddr,
}

impl SequencerHandle {
    const fn new(
        executor_ref: ActorRef<ExecutorActor>,
        rpc_server_ref: ActorRef<RpcServerActor>,
        scheduler_ref: ActorRef<Scheduler>,
        addr: SocketAddr,
    ) -> Self {
        Self {
            executor_ref,
            rpc_server_ref,
            scheduler_ref,
            addr,
        }
    }

    /// Stops the sequencer and waits for every part of it to be gone.
    pub async fn shutdown(mut self) {
        let Self {
            executor_ref,
            rpc_server_ref,
            scheduler_ref,
            addr: _,
        } = &mut self;

        info!("Stopping Scheduler Actor...");
        if let Err(err) = scheduler_ref.stop_gracefully().await {
            error!("Failed to stop Scheduler Actor gracefully: {err}");
        }
        scheduler_ref.wait_for_shutdown().await;
        info!("Scheduler Actor stopped");

        info!("Stopping RPC Server Actor...");
        if let Err(err) = rpc_server_ref.stop_gracefully().await {
            error!("Failed to stop RPC Server Actor gracefully: {err}");
        }
        rpc_server_ref.wait_for_shutdown().await;
        info!("RPC Server Actor stopped");

        info!("Stopping Executor Actor...");
        if let Err(err) = executor_ref.stop_gracefully().await {
            error!("Failed to stop Executor Actor gracefully: {err}");
        }
        executor_ref.wait_for_shutdown().await;
        info!("Executor Actor stopped");
    }

    /// Wait for any of the sequencer tasks to fail and return the error.
    #[expect(
        clippy::integer_division_remainder_used,
        reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
    )]
    pub async fn failed(&mut self) -> Result<Never> {
        let Self {
            executor_ref,
            rpc_server_ref,
            scheduler_ref,
            addr: _,
        } = self;

        select! {
            () = executor_ref.wait_for_shutdown() => {
                Err(anyhow!("Executor actor has been stopped"))
            }
            () = rpc_server_ref.wait_for_shutdown() => {
                Err(anyhow!("RPC server actor has been stopped"))
            }
            () = scheduler_ref.wait_for_shutdown() => {
                Err(anyhow!("Scheduler actor has been stopped"))
            }
        }
    }

    /// Check if all Sequencer tasks are still running.
    ///
    /// Return `false` if any of the tasks has failed and `true` otherwise.
    /// Error of the failed task can be retrieved by awaiting on [`Self::failed()`].
    #[must_use]
    pub fn is_healthy(&self) -> bool {
        let Self {
            executor_ref,
            rpc_server_ref,
            scheduler_ref,
            addr: _,
        } = self;

        executor_ref.is_alive() && rpc_server_ref.is_alive() && scheduler_ref.is_alive()
    }

    #[must_use]
    pub const fn addr(&self) -> SocketAddr {
        self.addr
    }
}

pub async fn run(config: SequencerConfig, listen_addr: SocketAddr) -> Result<SequencerHandle> {
    let block_timeout = config.block_create_timeout;
    let max_block_size = config.max_block_size;

    let executor_ref = ExecutorActor::spawn(ExecutorActor::new(config).await);
    info!("Executor Actor spawned");

    let rpc_server = RpcServerActor::new(executor_ref.clone(), listen_addr, max_block_size).await?;
    let addr = rpc_server.addr();
    let rpc_server_ref = RpcServerActor::spawn(rpc_server);
    info!("RPC Server Actor spawned");

    let scheduler_ref = Scheduler::spawn(Scheduler::new());
    scheduler_ref
        .tell(SetInterval::new(
            executor_ref.downgrade(),
            block_timeout,
            sequencer_executor_actor::protocol::ProduceBlock,
        ))
        .await?;
    info!("Block production scheduler started");

    Ok(SequencerHandle::new(
        executor_ref,
        rpc_server_ref,
        scheduler_ref,
        addr,
    ))
}
