use std::{
    net::{IpAddr, SocketAddr},
    path::PathBuf,
};

use anyhow::{Context as _, Result};
use clap::Parser;
use log::{error, info};
use metrics_exporter_prometheus::{Matcher, PrometheusBuilder};
use tokio::signal::unix::{SignalKind, signal};
use tokio_util::sync::CancellationToken;

#[derive(Debug, Parser)]
#[clap(version)]
struct Args {
    #[clap(name = "config")]
    config_path: PathBuf,
    #[clap(short, long, default_value = "3040")]
    port: u16,
    /// Interface the RPC server binds to. The RPC has no caller auth —
    /// bind loopback unless the port is firewalled.
    #[clap(long, default_value = "0.0.0.0")]
    listen_address: IpAddr,
    /// Override the config's home directory (`RocksDB` + bedrock signing key),
    /// so multiple instances can share one config file.
    #[clap(long)]
    home: Option<PathBuf>,
}

#[tokio::main]
#[expect(
    clippy::integer_division_remainder_used,
    reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
)]
async fn main() -> Result<()> {
    env_logger::init();

    install_prometheus_recorder()?;

    let Args {
        config_path,
        port,
        listen_address,
        home,
    } = Args::parse();

    let cancellation_token = listen_for_shutdown_signal();

    let mut config = sequencer_service::SequencerConfig::from_path(&config_path)?;
    if let Some(home) = home {
        config.home = home;
    }
    let mut sequencer_handle =
        sequencer_service::run(config, SocketAddr::new(listen_address, port)).await?;

    tokio::select! {
        () = cancellation_token.cancelled() => {
            info!("Shutting down sequencer...");
        }
        Err(err) = sequencer_handle.failed() => {
            error!("Sequencer failed unexpectedly: {err}");
        }
    }

    // Stop the watchers, the publisher's drive task, the block loop and the RPC
    // server, and wait for each. Dropping the handle only asks; the store stays
    // open for an unbounded stretch after that, so a restart can find its own
    // home directory locked, and a watcher can be killed between recording a
    // delivery and handing it over.
    sequencer_handle.shutdown().await;

    info!("Sequencer shutdown complete");

    Ok(())
}

/// Installs the recorder with explicit buckets, which makes every histogram
/// export as a Prometheus histogram (`_bucket`/`_sum`/`_count`) rather than the
/// default rolling-window summary. Summary quantiles reset to zero once their
/// window drains, so an idle period reads as "took 0s" instead of "no data".
///
/// Ladders are picked by name suffix, so a new timing metric is covered without
/// touching this function. The matcher sees the name as registered, *before*
/// [`PrometheusBuilder::with_recommended_naming`] appends a unit suffix of its
/// own — a duration metric whose name omits `_seconds` silently falls through to
/// [`COUNT_BUCKETS`].
fn install_prometheus_recorder() -> Result<()> {
    /// Ladder for `*_seconds` histograms, densest across the 1–100 ms band where
    /// block production and transaction application actually land.
    const LATENCY_BUCKETS: &[f64] = &[
        0.0005, 0.001, 0.0025, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0,
    ];

    /// Fallback ladder for histograms that count things rather than measure time.
    const COUNT_BUCKETS: &[f64] = &[1.0, 2.0, 5.0, 10.0, 25.0, 50.0, 100.0, 250.0, 500.0, 1000.0];

    PrometheusBuilder::new()
        .with_recommended_naming(true)
        .set_buckets(COUNT_BUCKETS)
        .context("Failed to set default histogram buckets")?
        .set_buckets_for_metric(Matcher::Suffix("_seconds".to_owned()), LATENCY_BUCKETS)
        .context("Failed to set latency histogram buckets")?
        .install()
        .context("Failed to install Prometheus recorder")
}

/// Cancelled on Ctrl-C or `SIGTERM`.
///
/// `SIGTERM` is what a container runtime sends first, so without it every
/// orchestrated stop is the ungraceful path.
#[expect(
    clippy::integer_division_remainder_used,
    reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
)]
fn listen_for_shutdown_signal() -> CancellationToken {
    let cancellation_token = CancellationToken::new();
    let cancellation_token_clone = cancellation_token.clone();

    tokio::spawn(async move {
        let mut terminate = match signal(SignalKind::terminate()) {
            Ok(terminate) => terminate,
            Err(err) => {
                error!("Failed to listen for SIGTERM: {err}");
                return;
            }
        };

        tokio::select! {
            result = tokio::signal::ctrl_c() => match result {
                Ok(()) => info!("Received Ctrl-C signal"),
                Err(err) => {
                    error!("Failed to listen for Ctrl-C signal: {err}");
                    return;
                }
            },
            _ = terminate.recv() => info!("Received SIGTERM"),
        }

        cancellation_token_clone.cancel();
    });

    cancellation_token
}
