use std::{
    net::{IpAddr, SocketAddr},
    path::PathBuf,
};

use anyhow::Result;
use clap::Parser;
use log::{error, info};
use tokio::signal::unix::{SignalKind, signal};
use tokio_util::sync::CancellationToken;

#[derive(Debug, Parser)]
#[clap(version)]
struct Args {
    #[clap(name = "config")]
    config_path: PathBuf,
    #[clap(short, long, default_value = "3040")]
    port: u16,
    /// Interface the RPC server binds to. The RPC has no caller auth —
    /// bind loopback unless the port is firewalled.
    #[clap(long, default_value = "0.0.0.0")]
    listen_address: IpAddr,
    /// Override the config's home directory (`RocksDB` + bedrock signing key),
    /// so multiple instances can share one config file.
    #[clap(long)]
    home: Option<PathBuf>,
}

#[tokio::main]
#[expect(
    clippy::integer_division_remainder_used,
    reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
)]
async fn main() -> Result<()> {
    env_logger::init();

    let Args {
        config_path,
        port,
        listen_address,
        home,
    } = Args::parse();

    let cancellation_token = listen_for_shutdown_signal();

    let mut config = sequencer_service::SequencerConfig::from_path(&config_path)?;
    if let Some(home) = home {
        config.home = home;
    }
    let mut sequencer_handle =
        sequencer_service::run(config, SocketAddr::new(listen_address, port)).await?;

    tokio::select! {
        () = cancellation_token.cancelled() => {
            info!("Shutting down sequencer...");
        }
        Err(err) = sequencer_handle.failed() => {
            error!("Sequencer failed unexpectedly: {err}");
        }
    }

    // Stop the watchers, the publisher's drive task, the block loop and the RPC
    // server, and wait for each. Dropping the handle only asks; the store stays
    // open for an unbounded stretch after that, so a restart can find its own
    // home directory locked, and a watcher can be killed between recording a
    // delivery and handing it over.
    sequencer_handle.shutdown().await;

    info!("Sequencer shutdown complete");

    Ok(())
}

/// Cancelled on Ctrl-C or `SIGTERM`.
///
/// `SIGTERM` is what a container runtime sends first, so without it every
/// orchestrated stop is the ungraceful path.
#[expect(
    clippy::integer_division_remainder_used,
    reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
)]
fn listen_for_shutdown_signal() -> CancellationToken {
    let cancellation_token = CancellationToken::new();
    let cancellation_token_clone = cancellation_token.clone();

    tokio::spawn(async move {
        let mut terminate = match signal(SignalKind::terminate()) {
            Ok(terminate) => terminate,
            Err(err) => {
                error!("Failed to listen for SIGTERM: {err}");
                return;
            }
        };

        tokio::select! {
            result = tokio::signal::ctrl_c() => match result {
                Ok(()) => info!("Received Ctrl-C signal"),
                Err(err) => {
                    error!("Failed to listen for Ctrl-C signal: {err}");
                    return;
                }
            },
            _ = terminate.recv() => info!("Received SIGTERM"),
        }

        cancellation_token_clone.cancel();
    });

    cancellation_token
}
